openapi: 3.0.3
info:
  title: Entitys API
  description: API to retrieve a single Entity by its identifier.
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local server

paths:
  /entitys/{id}:
    get:
      tags:
        - Entitys
      summary: Get a entity by ID
      description: Returns the **Entity** resource whose `id` matches the supplied path parameter.
      operationId: getEntityById
      parameters:
        - name: id
          in: path
          required: true
          description: Numeric identifier of the game to retrieve.
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Entity found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntityResponse'
        '400':
          description: Bad request - invalid or missing parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: No Entity found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    EntityResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
    ErrorResponse:
      type: object
      required:
        - timestamp
        - status
        - message
      properties:
        timestamp:
          type: string
          format: date-time
        status:
          type: integer
          format: int32
        message:
          type: string
        path:
          type: string
          description: Requested path (optional)